### ISSUE TITLE
UI Testing with Nightwatch.js, Headless Chrome, and Docker

### ISSUE THREAD

**Issue by smriti2324** [smriti2324/smriti-sharan#1]
Docker is setup properly according to me. I have installed all the dependencies like nodejs, java, npm ,xvfb(headless) but the test is failing showing selenium error. can someone help me debugging this issue. The same thing happened when I was running test in jenkins server. Test were not running. But locally test run perfect. 

I am not able to determine the reason. Even my teamate help I took we spent sometime but still not able to detect the exact problem. I can share my project with you and docker image just to see.

**Comment by smriti2324** [comment]
Error retrieving a new session from the selenium server



Error writing log file to: /home/Automation-Infra-analytics-UI-Test/log/selenium-debug.log



Connection refused! Is selenium server started?

{ Error: socket hang up

    at createHangUpError (_http_client.js:345:15)

    at Socket.socketCloseListener (_http_client.js:377:23)

    at emitOne (events.js:120:20)

    at Socket.emit (events.js:210:7)

    at TCP._handle.close [as _onclose] (net.js:545:12) code: 'ECONNRESET' }





npm ERR! Linux 4.9.36-moby

npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test-headless"

npm ERR! node v4.2.6

npm ERR! npm  v3.5.2

npm ERR! code ELIFECYCLE

npm ERR! infra-analytics-ui-test@1.0.0 test-headless: `xvfb-run ./node_modules/.bin/nightwatch`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the infra-analytics-ui-test@1.0.0 test-headless script 'xvfb-run ./node_modules/.bin/nightwatch'.

npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the infra-analytics-ui-test package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     xvfb-run ./node_modules/.bin/nightwatch

npm ERR! You can get information on how to open an issue for this project with:

npm ERR!     npm bugs infra-analytics-ui-test

npm ERR! Or if that isn't available, you can get their info via:

npm ERR!     npm owner ls infra-analytics-ui-test

npm ERR! There is likely additional logging output above.



npm ERR! Please include the following file with any support request:

npm ERR!     /home/Automation-Infra-analytics-UI-Test/npm-debug.log

root@1435e1aac7a8:/home/Automation-Infra-analytics-UI-Test#
